### PR TITLE
fix(ui): removes close and maximise buttons

### LINKED ISSUE #132: Reopen a panel that was closed
It's possible to close a panel, but how can I reopen it?

# How to reproduce
* Click on any panel
* Hit the `delete` key
* See that the panel is gone

# Ideas
* Use `ctrl + z` to undo the panel close?
* Use `View` or `Window` to reopen a panel

### PR DESCRIPTION
**Pull request by 2xAA**
Disables Golden Layout's UI control buttons

fixes #132

### CODE REVIEW

**Comment by TimPietrusky** [comment]
I run into this error while testing, which results in no panel showing at all:

```
Uncaught TypeError: Cannot read property 'childMe' of undefined
    at VueComponent../roles/container.ts.goldenContainer.vueChild
```

I did run `yarn` before doing anything.

**Comment by 2xAA** [comment]
Can you send me your layout state again?
I'm not getting the error but the changes made won't take effect if there's already a layout state saved it seems.

**Comment by TimPietrusky** [comment]
I copied the state from https://github.com/vcync/modv-3/pull/167#issuecomment-647138726 and replaced mine, as I thought that mine might be broken. But the result was the same = I get the error message above.

**Comment by 2xAA** [comment]
@TimPietrusky Yes, I can reproduce this here too with the state from #167.

Wiping the layoutState and reloading gets around this, though not ideal it could be a viable solution for now as this is only in-dev. Production versions of the app do not have the layoutState key yet in localStorage.

It's a pain as `vue-golden-layout` does not forward Golden Layout's errors to Vue so the only way to catch these is to add a function to `window.onerror` and listen for the message string matching the above. A sample of this approach can be found on https://github.com/vcync/modv-3/tree/fix/layoutRestorationError.

I've created an issue on `vue-golden-layout`'s repo (https://github.com/emedware/vue-golden-layout/issues/78) and I'm hoping we can implement or find a better way to catch the error.

**Review by TimPietrusky — APPROVED** [review]
It works when I remove the `layoutState` from localStorage.

**Pull request merged**
