### PR TITLE
feat(global-search): adds global-search component and directive

### LINKED ISSUE #178: Global search
(split from #166)

Implement a global search, similar to macOS' default System Preferences search box where it highlights which PrefPane contains the setting you're looking for.

Other examples could be macOS' "Help > Search" menubar item, Spotlight search or Ubuntu's application search.

This would be helpful as modV has many parameters, sometimes hard to find.

### PR DESCRIPTION
**Pull request by 2xAA**
Adds Global Search component and Vue directive.
Adds extended background-color.
Introduces fuse.js as a dependancy.

fixes #178

### CODE REVIEW

**Comment by 2xAA** [comment]
Use cmd/ctrl + shift + f to bring up the search.

**Review by TimPietrusky — CHANGES_REQUESTED** [review]
1. Please document the two different search combinations and locations (module search vs global search)
2. Please document how to add `searchTerms` into modules

**Comment by 2xAA** [comment]
@TimPietrusky I've just launched a new docs site (https://modv.vcync.gl/) which has v3 docs on there.

So hopefully these satisfy for now.

1. https://modv.vcync.gl/v3/guide/shortcuts.html
2. https://modv.vcync.gl/v3/development/directives.html

**Review by TimPietrusky — APPROVED** [review]
LGTM

**Pull request merged**
