### PR TITLE
feat(panel-position): adds saving panel positions to local storage

### LINKED ISSUE #131: Save the panel position state
It's already possible to change the position of every panel, but that is not saved anywhere. 

h2. Desired Behavior
I change the position of the panels and it gets stored, so I can restart modV and still have the same panel positions as before

### PR DESCRIPTION
**Pull request by 2xAA**
Upgrades vue-golden-layout so we can use Golden Layout componentState to track panels we need to
remove from Golden Layout state when saving.

fixes #131

### CODE REVIEW

**Comment by 2xAA** [comment]
I need to document that purgeDynamicPanels function still, but if you could test this @TimPietrusky would be helpful.

Works here.

**Comment by TimPietrusky** [comment]
@2xAA I tested this:

- Start modV (`yarn electron:serve`) and change the position of some panels
- Save a preset (but I guess this is not required as I couldn't find any information about the panel layout in the preset.json)
- Exit modV
- Start modV
- See that the layout can't be recovered

Screenshot 2020-06-20 at 10 22 00

**Review by TimPietrusky — CHANGES_REQUESTED** [review]
It's not working, please find out why or let me know in which direction I should look into.

**Comment by 2xAA** [comment]
@TimPietrusky Would you mind attaching the preset you saved so I can reproduce your state?

Layout is saved in local storage and not the preset.

Though in hindsight maybe we should save this to the project?

**Comment by TimPietrusky** [comment]
@2xAA is the local storage also persisted?

Preset: [test.json.zip](https://github.com/vcync/modv-3/files/4808074/test.json.zip)

**Comment by 2xAA** [comment]
Yes, Electron apps persist local storage between sessions as Chrome would.

Thanks for the preset!

**Comment by 2xAA** [comment]
**!! EDIT Before clearing your local storage, please copy and paste the string into a comment here so I can analyse the layout state.**

@TimPietrusky I can't seem to reproduce this. Can you try clearing your local storage and trying again?
I've cleared the local storage here, moved every panel, pinned some dynamically added module property panels, moved them too and it restores the layout without problem.

If possible, record a video of the steps outlined above too.

**Comment by TimPietrusky** [comment]
@2xAA here comes the layoutState from LocalStorage. 

```
{"0":{"1":"0","2":"0","3":"1","t":"0","p":"0","blockedPopoutsThrowError":"0","closePopoutsOnUnload":"0","showPopoutIcon":"1","showMaximiseIcon":"0","showCloseIcon":"0","responsiveMode":"onload","tabOverlapAllowance":0,"reorderOnTabMenuClick":"0","tabControlOffset":10},"4":{"5":5,"6":10,"7":10,"8":20,"9":300,"u":15,"a":200},"b":{"c":"6","d":"7","e":"8","f":"9","popin":"pop in","tabDropdown":"additional tabs"},"g":[{"n":"0","l":"3","t":"0","vue":"___0","o":"","g":[{"n":"0","l":"2","t":"0","vue":"0.0","o":"","m":70.31963470319634,"g":[{"n":"1","l":"3","t":"0","vue":"0.0.0","o":"","k":67,"g":[{"s":0,"n":"0","l":"4","t":"0","o":"Groups Stack","vue":"0.0.0.0","m":100,"g":[{"l":"5","n":"1","t":"0","o":"Groups","vue":"0.0.0.0.0","h":"Generic.Vue","i":{}}]}]},{"k":33,"n":"1","l":"3","t":"0","vue":"0.0.1","o":"","g":[{"l":"4","header":{},"n":"0","t":"0","o":"","s":0,"m":50,"g":[{"l":"5","n":"1","t":"0","o":"Preview","vue":"0.1.2.0","h":"Generic.Vue","i":{}}]},{"s":1,"n":"0","l":"4","t":"0","o":"Module Inspector Stack","vue":"0.0.1.0","m":50,"k":100,"g":[{"l":"5","n":"0","t":"0","o":"hidden","vue":"0.0.1.0.0","h":"Generic.Vue","i":{}},{"l":"5","n":"1","t":"0","o":"Ball properties","vue":"0.0.1.0.1","h":"Generic.Vue","i":{}}]}]}]},{"n":"0","l":"2","t":"0","vue":"0.1","o":"","m":29.680365296803657,"g":[{"l":"4","k":33.333333333333336,"n":"0","t":"0","o":"","s":0,"g":[{"l":"5","n":"1","t":"0","o":"Gallery","vue":"0.1.0","h":"Generic.Vue","i":{}}]},{"s":0,"n":"0","l":"4","t":"0","o":"Input Stack","vue":"0.1.1","k":52.8488111260655,"g":[{"l":"5","n":"1","t":"0","o":"Input config","vue":"0.1.1.0","h":"Generic.Vue","i":{}},{"s":0,"n":"1","l":"4","t":"0","o":"Input Device Config","vue":"0.1.1.1","g":[{"l":"5","n":"1","t":"0","o":"Audio","vue":"0.1.1.1.0","h":"Generic.Vue","i":{}},{"l":"5","n":"1","t":"0","o":"MIDI","vue":"0.1.1.1.1","h":"Generic.Vue","i":{}},{"l":"5","n":"1","t":"0","o":"BPM","vue":"0.1.1.1.2","h":"Generic.Vue","i":{}},{"l":"5","n":"1","t":"0","o":"NDI","vue":"0.1.1.1.3","h":"Generic.Vue","i":{}}]}]},{"s":0,"n":"0","l":"4","t":"0","o":"Preview Stack","vue":"0.1.2","k":13.817855540601169,"g":[{"l":"5","n":"1","t":"0","o":"Swap","vue":"0.1.2.1","h":"Generic.Vue","i":{}}]}]}]}],"n":"0","t":"0","o":"","q":[],"maximisedItemId":{}}
```

**Comment by 2xAA** [comment]
@TimPietrusky Thank you for the state. I think I know what the problem is.

Did you update packages before running `yarn electron:serve`?
I mention above that vue-golden-layout needed upgrading.

Your state contains a dynamically added panel without the Golden Layout component state saved, so we can't track the panels which need to be removed for the state to restore correctly.

**Comment by 2xAA** [comment]
You can test this by:

1. running `yarn`
2. modifying line 163 of App.vue with `this.layoutState = this.purgeDynamicPanels(JSON.parse(layoutState));`
3. setting the localStorage key to the following unminified state with `{"is":"dynamic"}` set on "Ball properties" componentState key (the edit has been performed, you only need to copy and paste)

```JSON
{"settings":{"hasHeaders":true,"constrainDragToContainer":true,"selectionEnabled":false,"reorderEnabled":true,"popoutWholeStack":true,"blockedPopoutsThrowError":true,"closePopoutsOnUnload":true,"showPopoutIcon":false,"showMaximiseIcon":true,"showCloseIcon":true,"responsiveMode":"onload","tabOverlapAllowance":0,"reorderOnTabMenuClick":true,"tabControlOffset":10},"dimensions":{"borderWidth":5,"minItemHeight":10,"minItemWidth":10,"headerHeight":20,"dragProxyWidth":300,"borderGrabWidth":15,"dragProxyHeight":200},"labels":{"close":"close","maximise":"maximise","minimise":"minimise","popout":"open in new window","popin":"pop in","tabDropdown":"additional tabs"},"content":[{"isClosable":true,"type":"column","reorderEnabled":true,"vue":"0","title":"","content":[{"isClosable":true,"type":"row","reorderEnabled":true,"vue":"0.0","title":"","height":70.31963470319634,"content":[{"isClosable":false,"type":"column","reorderEnabled":true,"vue":"0.0.0","title":"","width":67,"content":[{"activeItemIndex":0,"isClosable":true,"type":"stack","reorderEnabled":true,"title":"Groups Stack","vue":"0.0.0.0","height":100,"content":[{"type":"component","isClosable":false,"reorderEnabled":true,"title":"Groups","vue":"0.0.0.0.0","componentName":"Generic.Vue","componentState":{}}]}]},{"width":33,"isClosable":false,"type":"column","reorderEnabled":true,"vue":"0.0.1","title":"","content":[{"type":"stack","header":{},"isClosable":true,"reorderEnabled":true,"title":"","activeItemIndex":0,"height":50,"content":[{"type":"component","isClosable":false,"reorderEnabled":true,"title":"Preview","vue":"0.1.2.0","componentName":"Generic.Vue","componentState":{}}]},{"activeItemIndex":1,"isClosable":true,"type":"stack","reorderEnabled":true,"title":"Module Inspector Stack","vue":"0.0.1.0","height":50,"width":100,"content":[{"type":"component","isClosable":true,"reorderEnabled":true,"title":"hidden","vue":"0.0.1.0.0","componentName":"Generic.Vue","componentState":{}},{"type":"component","isClosable":false,"reorderEnabled":true,"title":"Ball properties","vue":"0.0.1.0.1","componentName":"Generic.Vue","componentState":{"is":"dynamic"}}]}]}]},{"isClosable":true,"type":"row","reorderEnabled":true,"vue":"0.1","title":"","height":29.680365296803657,"content":[{"type":"stack","width":33.333333333333336,"isClosable":true,"reorderEnabled":true,"title":"","activeItemIndex":0,"content":[{"type":"component","isClosable":false,"reorderEnabled":true,"title":"Gallery","vue":"0.1.0","componentName":"Generic.Vue","componentState":{}}]},{"activeItemIndex":0,"isClosable":true,"type":"stack","reorderEnabled":true,"title":"Input Stack","vue":"0.1.1","width":52.8488111260655,"content":[{"type":"component","isClosable":false,"reorderEnabled":true,"title":"Input config","vue":"0.1.1.0","componentName":"Generic.Vue","componentState":{}},{"activeItemIndex":0,"isClosable":false,"type":"stack","reorderEnabled":true,"title":"Input Device Config","vue":"0.1.1.1","content":[{"type":"component","isClosable":false,"reorderEnabled":true,"title":"Audio","vue":"0.1.1.1.0","componentName":"Generic.Vue","componentState":{}},{"type":"component","isClosable":false,"reorderEnabled":true,"title":"MIDI","vue":"0.1.1.1.1","componentName":"Generic.Vue","componentState":{}},{"type":"component","isClosable":false,"reorderEnabled":true,"title":"BPM","vue":"0.1.1.1.2","componentName":"Generic.Vue","componentState":{}},{"type":"component","isClosable":false,"reorderEnabled":true,"title":"NDI","vue":"0.1.1.1.3","componentName":"Generic.Vue","componentState":{}}]}]},{"activeItemIndex":0,"isClosable":true,"type":"stack","reorderEnabled":true,"title":"Preview Stack","vue":"0.1.2","width":13.817855540601169,"content":[{"type":"component","isClosable":false,"reorderEnabled":true,"title":"Swap","vue":"0.1.2.1","componentName":"Generic.Vue","componentState":{}}]}]}]}],"isClosable":true,"reorderEnabled":true,"title":"","openPopouts":[],"maximisedItemId":{}}
```

We should not need the modification to line 163 in production as the removal of dynamic panels happens when state is saved.

**Comment by TimPietrusky** [comment]
@2xAA works as expected.

**Review by TimPietrusky — APPROVED** [review]
LGTM

**Pull request merged**
